version: "3.3"

services:
  app-cineplay:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-cineplay-app
    environment:
      CHOKIDAR_USEPOLLING: 'true'
    ports:
      - "8000:80"
    volumes:
      - ".:/var/www"
    networks:
      - cineplay
    depends_on:
      - redis
      - mysql
      - phpmyadmin

  redis:
    image: "redis:alpine"
    container_name: api-cineplay-redis
    ports:
      - "${FORWARD_REDIS_PORT:-6379}:6379"
    volumes:
      - "redis:/data"
    networks:
      - cineplay
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      retries: 3
      timeout: 5s

  mysql:
    container_name: api-cineplay-db
    image: mysql:latest
    restart: always
    environment:
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - "database:/var/lib/mysql"
    networks:
      - cineplay

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - mysql
    ports:
      - 8001:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - cineplay

networks:
  cineplay:
    driver: bridge

volumes:
  redis:
    driver: local
  database:
    driver: local
